name: om_health_care_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  http: ^1.5.0
  shared_preferences: ^2.5.3
  socket_io_client: ^3.1.2
  mime: ^2.0.0
  image_picker: ^1.2.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  geolocator: ^13.0.3
  shimmer: ^3.0.0
  intl: ^0.20.2
  swipe_to: ^1.0.6
  video_player: ^2.10.0
  audioplayers: ^6.5.1
  photo_view: ^0.15.0
  open_filex: ^4.7.0
  url_launcher: ^6.3.2
  file_picker: ^10.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true
  assets:
    - assets/icon/